version: "2.4"
services:
  weston:
    environment:
      - ACCEPT_FSL_EULA=1
    container_name: weston-battery
    image: torizon/arm32v7-debian-weston
    # Required to get udev events from host udevd via netlink
    network_mode: host
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev
    # this cap is need only for kiosk on Apalis iMX6
    cap_add:
      - CAP_SYS_TTY_CONFIG
    # Add device access rights through cgroup...
    device_cgroup_rules:
      # ... for tty0
      - "c 4:0 rmw"
      # ... for tty7
      - "c 4:7 rmw"
      # ... for /dev/input devices
      - "c 13:* rmw"
      - "c 199:* rmw"
      # ... for /dev/dri devices
      - "c 226:* rmw"

  app:
    container_name: battery-sample
    image: matheuscastello/torizon-battery-sample
    privileged: true
    network_mode: host
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /var/run/dbus
        target: /var/run/dbus
      - type: bind
        source: /dev/dri
        target: /dev/dri
      - type: bind
        source: /run/udev
        target: /run/udev
      - /sys:/sys:rw
      - /etc/os-release:/etc/os-release:ro
    # this cap is the new root
    cap_add:
      - CAP_SYS_ADMIN
    depends_on:
      - weston
    shm_size: "256mb"
    device_cgroup_rules:
      # ... for /dev/dri devices
      - "c 226:* rmw"
    stdin_open: true # docker run -i
    tty: true        # docker run -
